'use client'

import { useState } from 'react'
import { Property } from '@/lib/property-schema'
import { formatCurrency, formatNumber } from '@/lib/format'
import { jsPDF } from 'jspdf'

interface ExportComparisonProps {
  property1: Property
  property2: Property
  comparisons: {
    financial: Array<{ label: string; value1: string | number | null | undefined; value2: string | number | null | undefined }>
    size: Array<{ label: string; value1: string | number | null | undefined; value2: string | number | null | undefined }>
    neighborhood: Array<{ label: string; value1: string | number | null | undefined; value2: string | number | null | undefined }>
  }
}

export function ExportComparison({ property1, property2, comparisons }: ExportComparisonProps) {
  const [isExporting, setIsExporting] = useState(false)

  const generatePDF = async () => {
    setIsExporting(true)
    
    try {
      const doc = new jsPDF()
      const pageWidth = doc.internal.pageSize.getWidth()
      let y = 20

      // Title
      doc.setFontSize(20)
      doc.setFont('helvetica', 'bold')
      doc.text('Property Comparison Report', pageWidth / 2, y, { align: 'center' })
      y += 15

      // Date
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100)
      doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, y, { align: 'center' })
      y += 20

      // Property Headers
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(0)
      
      const col1X = 20
      const col2X = pageWidth / 2 + 10

      // Property 1
      doc.text('Property 1', col1X, y)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
      y += 7
      doc.text(property1.address, col1X, y)
      y += 5
      doc.setTextColor(100)
      doc.text(`${property1.city}, ${property1.state} ${property1.zipCode}`, col1X, y)
      y += 5
      doc.setTextColor(0)
      doc.setFont('helvetica', 'bold')
      doc.text(formatCurrency(property1.price), col1X, y)
      
      // Property 2 (same Y level)
      let y2 = y - 17
      doc.setFontSize(12)
      doc.text('Property 2', col2X, y2)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
      y2 += 7
      doc.text(property2.address, col2X, y2)
      y2 += 5
      doc.setTextColor(100)
      doc.text(`${property2.city}, ${property2.state} ${property2.zipCode}`, col2X, y2)
      y2 += 5
      doc.setTextColor(0)
      doc.setFont('helvetica', 'bold')
      doc.text(formatCurrency(property2.price), col2X, y2)
      
      y += 20

      // Quick Stats
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.text(`${property1.bedrooms} bd | ${property1.bathrooms} ba | ${formatNumber(property1.sqft)} sqft`, col1X, y)
      doc.text(`${property2.bedrooms} bd | ${property2.bathrooms} ba | ${formatNumber(property2.sqft)} sqft`, col2X, y)
      
      y += 15

      // Comparison Table Helper
      const drawTable = (title: string, items: Array<{ label: string; value1: string | number | null | undefined; value2: string | number | null | undefined }>) => {
        if (y > 250) {
          doc.addPage()
          y = 20
        }

        doc.setFontSize(12)
        doc.setFont('helvetica', 'bold')
        doc.text(title, col1X, y)
        y += 8

        doc.setFontSize(9)
        doc.setFont('helvetica', 'normal')

        items.forEach(item => {
          if (y > 270) {
            doc.addPage()
            y = 20
          }

          const val1 = formatValue(item.value1)
          const val2 = formatValue(item.value2)

          doc.setTextColor(100)
          doc.text(item.label, col1X, y)
          doc.setTextColor(0)
          doc.text(val1, col1X + 50, y)
          doc.text(val2, col2X + 30, y)
          y += 6
        })

        y += 10
      }

      // Draw all tables
      drawTable('Financial Comparison', comparisons.financial)
      drawTable('Size & Features', comparisons.size)
      drawTable('Neighborhood & Location', comparisons.neighborhood)

      // Footer
      doc.setFontSize(8)
      doc.setTextColor(150)
      doc.text('Generated by PropInsight', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' })

      // Save
      doc.save(`property-comparison-${Date.now()}.pdf`)
    } catch (error) {
      console.error('Error generating PDF:', error)
    } finally {
      setIsExporting(false)
    }
  }

  const formatValue = (value: string | number | null | undefined): string => {
    if (value === null || value === undefined) return '--'
    if (typeof value === 'number') {
      if (value >= 1000) return formatCurrency(value)
      return formatNumber(value)
    }
    return String(value)
  }

  const copyToClipboard = async () => {
    const text = generateTextSummary()
    await navigator.clipboard.writeText(text)
  }

  const generateTextSummary = () => {
    let text = 'PROPERTY COMPARISON REPORT\n'
    text += `Generated: ${new Date().toLocaleDateString()}\n\n`
    
    text += '--- PROPERTY 1 ---\n'
    text += `${property1.address}\n`
    text += `${property1.city}, ${property1.state} ${property1.zipCode}\n`
    text += `Price: ${formatCurrency(property1.price)}\n`
    text += `${property1.bedrooms} bed | ${property1.bathrooms} bath | ${formatNumber(property1.sqft)} sqft\n\n`
    
    text += '--- PROPERTY 2 ---\n'
    text += `${property2.address}\n`
    text += `${property2.city}, ${property2.state} ${property2.zipCode}\n`
    text += `Price: ${formatCurrency(property2.price)}\n`
    text += `${property2.bedrooms} bed | ${property2.bathrooms} bath | ${formatNumber(property2.sqft)} sqft\n\n`
    
    text += '--- COMPARISON ---\n'
    const allComparisons = [...comparisons.financial, ...comparisons.size, ...comparisons.neighborhood]
    allComparisons.forEach(item => {
      text += `${item.label}: ${formatValue(item.value1)} vs ${formatValue(item.value2)}\n`
    })

    return text
  }

  return (
    <div className="flex items-center gap-2">
      <button
        onClick={copyToClipboard}
        className="inline-flex items-center gap-2 border border-ink/30 bg-card text-foreground px-4 py-2 text-sm font-medium hover:bg-muted hover:border-ink transition-colors rounded-sm"
      >
        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
        </svg>
        Copy
      </button>

      <button
        onClick={generatePDF}
        disabled={isExporting}
        className="inline-flex items-center gap-2 border border-ink/30 bg-foreground text-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground hover:border-ink transition-colors disabled:opacity-50 rounded-sm"
      >
        {isExporting ? (
          <>
            <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
            </svg>
            Exporting…
          </>
        ) : (
          <>
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Export PDF
          </>
        )}
      </button>
    </div>
  )
}
